### ISSUE TITLE
Images not downloadable with right click + save

### ISSUE THREAD

**Issue by coldbae** [paulgoblin/jessy-lu#25]
Can you help make it such that the images can't be downloaded into a jpg file onto somone's computer? <3

**Comment by paulgoblin** [comment]
Fixed by https://github.com/paulgoblin/jessy-lu/commit/fb0889f355db65239f2b5719148a0e346df2fd50 and published in https://github.com/paulgoblin/jessy-lu/commit/609b15930a85b07d7dfe86dc7e5d51e87d67a032
